sudo: true
language: android
notifications: 
    email:
        - ibnu.muzzakkir@amarbank.com 
android:
  components:
    - platform-tools
    - tools
    - build-tools-24.0.2
    - android-22
    - android-24
    - sys-img-armeabi-v7a-android-22
    - extra-android-m2repository
# install dependencies
install: 
  - "sudo pip install 'requests[security]'"
  - "sudo pip install robotframework-appiumlibrary" 
  - "sudo apt-get update"
  - "sudo apt-get install nodejs" 
  - "sudo apt-get install npm"
  - "npm install -g appium"
before_script: 
# Create and start emulator
  - echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
  - "appium &"
  - "sleep 8s"
script: "pybot MovieAppTest.robot"